language: python
os: linux
dist: bionic
services:
  - docker
python:
  - "3.7"
install: pip install tox-travis
jobs:
  include:
    - stage: test
      name: Python Tox Tests
      script: tox
    - stage: test
      name: CSS Tests
      script: docker-compose run css-test
