version: "3"
services:
  css-test:
    image: felixedel/flirror-css:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=flirror:create_web
      - FLIRROR_SETTINGS=/src/tests/testdata/test-settings.cfg
      - TEST_DB_SCRIPT=/src/tests/testdata/database-dump.sql
    volumes:
      # Mount the local src dir into the container to test the current
      # development version.
      - .:/src
    command: test
  css-reference:
    # TODO (felix): Is there a way to reuse the parameters
    # from the "css-test" service?
    image: felixedel/flirror-css:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=flirror:create_web
      - FLIRROR_SETTINGS=/src/tests/testdata/test-settings.cfg
      - TEST_DB_SCRIPT=/src/tests/testdata/database-dump.sql
    volumes:
      # Mount the local src dir into the container to test the current
      # development version.
      - .:/src
    command: reference
  web:
    build:
      dockerfile: dockerfiles/flirror-Dockerfile
      context: .
    image: flirror
    ports:
      - "8000:8000"
    environment:
      - FLIRROR_SETTINGS=/opt/settings.cfg
    volumes:
      # TODO For production: No need to mount the whole workspace.
      # Only mount the settings.cfg and provide a docker volume
      # for the database
      - .:/opt
      #- ./settings.cfg:/opt/settings.cfg
  crawler:
    build:
      dockerfile: dockerfiles/flirror-Dockerfile
      context: .
    image: flirror
    environment:
      - FLIRROR_SETTINGS=/opt/settings.cfg
      - GOOGLE_OAUTH_CLIENT_SECRET=/opt/google_oauth_client_secret.json
    volumes:
      # TODO For production: No need to mount the whole workspace.
      # Only mount the settings.cfg and provide a docker volume
      # for the database
      - .:/opt
      #- ./settings.cfg:/opt/settings.cfg
    command: flirror-crawler crawl --periodic
